### ISSUE TITLE
User_id to user.id

### ISSUE THREAD

**Issue by stijnhau** [ZF-Commons/ZfcUser#589]
i prose changing for v2 the user_id field in the user table to id.
This is more logic in fact for database normalisation and.
Also this field is sometimes user_id in code and sometimes id. this should make it more logic.

**Comment by Danielss89** [comment]
Agree :)

**Comment by stijnhau** [comment]
Oke will change this as soon as i got time.
(Hoping this week)

**Comment by stijnhau** [comment]
litle bit latter then planned but the PR is there :)

**Comment by cbichis** [comment]
Yes, this change is a must.

Using user_id is below standards for a PK...

To integrate ZfcUser with an already "properly" made database we need to use own Mapper, Hydrator, etc...

Also, I do feel using state instead of states is a bad choice too... I never used state in a database field name unless is related to a region...

**Comment by stijnhau** [comment]
Maybe the PR can be merged in?

**Comment by Danielss89** [comment]
Merged
