### ISSUE TITLE
Changeable database field names

### ISSUE THREAD

**Issue by pierrejochem** [ZF-Commons/ZfcUser#676]
It would be awesome to have the posibility to change db field names via the configuration file.

e.g.: username, password, email, ...

**Comment by pierrejochem** [comment]
:-(

**Comment by jroedel** [comment]
Was this fixed?

**Comment by pierrejochem** [comment]
No, it wasn‘t :-(

**Comment by jroedel** [comment]
I would leave the issue open in that case. I think this is an important feature.

If the moderators of this repository are listening. I would propose and volunteer myself for a week period to bring this project up to snuff. I find this one of the most important packages for amateur ZF users like myself. I wouldn't call myself a PHP expert, but I've been using this package (slightly modified) in production environments since 2013.

I understand that no one has the energy or motivation to take on the pending changes themselves, but if we can get a little team of 3-4 capable programmers plus a couple other interested people (I don't count myself among the "capable") we could bring this back up to a useable level.

Anyone on board?
